# Generated by Django 2.1.5 on 2020-07-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ticket',
            field=models.CharField(default='6EBOVLWEBD02EPEVZRXQ3TTJO4DNWQ7L2UPQWVSHJIQGYEEKBW', max_length=50),
        ),
    ]
