# Generated by Django 2.1.5 on 2020-07-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20200724_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ticket',
            field=models.CharField(default='XEWV8QO3MG8WIUBNULHQSVDF3ELTITTAMXRBUPJ7POYF2NJI2Q', max_length=50),
        ),
    ]
