# Generated by Django 2.1.5 on 2020-07-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
                ('stacktrace', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LogEvolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.IntegerField(db_index=True)),
                ('timestamp', models.CharField(max_length=500)),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='LogInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.IntegerField(db_index=True)),
                ('timestamp', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=300)),
                ('log', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='errorlogobject',
            unique_together={('ticket', 'message', 'stacktrace')},
        ),
    ]
