# Generated by Django 2.1.5 on 2020-07-24 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='errorlogobject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='errorlogobject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='errorlogobject',
            name='message',
        ),
        migrations.RemoveField(
            model_name='errorlogobject',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='errorlogobject',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='errorlogobject',
            name='logobject_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logs_manager.LogObject'),
            preserve_default=False,
        ),
    ]
