# Generated by Django 2.1.5 on 2020-07-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs_manager', '0003_auto_20200724_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticLog',
            fields=[
                ('logobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logs_manager.LogObject')),
                ('stacktrace', models.TextField()),
                ('host', models.CharField(max_length=200)),
            ],
            bases=('logs_manager.logobject',),
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=200)),
            ],
        ),
    ]
