# Generated by Django 2.1.5 on 2020-07-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs_manager', '0004_analyticlog_userinteraction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinteraction',
            options={'ordering': ('analytic_log', 'timestamp')},
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='analytic_log',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='elementId',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='innerText',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='location',
            field=models.TextField(default='11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='timestamp',
            field=models.CharField(default='123435', max_length=200),
            preserve_default=False,
        ),
    ]
