# Generated by Django 2.1.5 on 2020-07-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs_manager', '0005_auto_20200724_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticlog',
            name='logobject_ptr',
        ),
        migrations.AlterModelOptions(
            name='userinteraction',
            options={'ordering': ('log_id', 'timestamp')},
        ),
        migrations.RenameField(
            model_name='userinteraction',
            old_name='analytic_log',
            new_name='log_id',
        ),
        migrations.DeleteModel(
            name='AnalyticLog',
        ),
    ]
