# Generated by Django 2.1.5 on 2020-07-24 07:27

from django.db import migrations, models
import logs_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('logs_manager', '0007_auto_20200724_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='timestamp',
            field=models.CharField(blank=True, default=logs_manager.models.UserInteraction.get_cur_str_time, max_length=200, null=True),
        ),
    ]
